# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_test <- function(a) {
    .Call('_iso8601_rcpp_test', PACKAGE = 'iso8601', a)
}

