# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_parse_iso_dateframe <- function(in_str, transformdate = 0L) {
    .Call('_iso8601_rcpp_parse_iso_dateframe', PACKAGE = 'iso8601', in_str, transformdate)
}

rcpp_parse_date <- function(in_str) {
    .Call('_iso8601_rcpp_parse_date', PACKAGE = 'iso8601', in_str)
}

rcpp_parse_datetime <- function(in_str, fillmissing = TRUE) {
    .Call('_iso8601_rcpp_parse_datetime', PACKAGE = 'iso8601', in_str, fillmissing)
}

rcpp_parse_time <- function(in_str) {
    .Call('_iso8601_rcpp_parse_time', PACKAGE = 'iso8601', in_str)
}

rcpp_standardise_datetime <- function(in_str, fillmissing = TRUE, toymd = TRUE, to_zulu = TRUE) {
    .Call('_iso8601_rcpp_standardise_datetime', PACKAGE = 'iso8601', in_str, fillmissing, toymd, to_zulu)
}

rcpp_standardise <- function(in_str, fillmissing = TRUE, toymd = TRUE, to_zulu = TRUE) {
    .Call('_iso8601_rcpp_standardise', PACKAGE = 'iso8601', in_str, fillmissing, toymd, to_zulu)
}

rcpp_type <- function(in_str) {
    .Call('_iso8601_rcpp_type', PACKAGE = 'iso8601', in_str)
}

